### PR TITLE
Support Iron 0.6

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by atorstling** [comment]
Hey @shepmaster ! Thanks for the bump. Looks like the trait was needed though: https://travis-ci.org/atorstling/corsware/jobs/302784669 . Or am I missing something?

**Comment by atorstling** [comment]
@shepmaster To spare you the effort, I'm bumping the versions and releasing separately from this PR.

**Comment by atorstling** [comment]
@shepmaster 0.2.0 released.

**Comment by shepmaster** [comment]
> Looks like the trait was needed though: https://travis-ci.org/atorstling/corsware/jobs/302784669 . Or am I missing something?

Yes, very strange. I definitely got a warning when building locally — I don't just remove random imports for fun 😇 

Thanks!

**Comment by atorstling** [comment]
@shepmaster Yeah, it has to do with the test setup. If I remember correctly that trait is already imported when compiling some compilation unit, but not when compiling another. Will look into it, might be a cargo quirk.

**Comment by shepmaster** [comment]
Oh! I think it might be https://github.com/rust-lang/rust/commit/1916e3c4aad7b0e0de1cfd190819609f55520996 — these methods now exist on the type proper. It's mostly a backwards compatibility thing now.

**Pull request closed without merging**
